import React, { useState } from 'react';
import { Header } from './components/Header';
import { AdvisorForm } from './components/AdvisorForm';
import { ReportView } from './components/ReportView';
import { generateRealEstateAdvice } from './services/geminiService';
import { RealEstateReport, UserPreferences } from './types';
import { AlertOctagon, FolderOpen } from 'lucide-react';

const App: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<RealEstateReport | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleFormSubmit = async (prefs: UserPreferences) => {
    setLoading(true);
    setError(null);
    setReport(null);

    try {
      const data = await generateRealEstateAdvice(prefs);
      setReport(data);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "An unexpected error occurred while fetching market data.");
    } finally {
      setLoading(false);
    }
  };

  const handleLoadSaved = () => {
    try {
      const saved = localStorage.getItem('propVisionReport');
      if (saved) {
        setReport(JSON.parse(saved));
        setError(null);
      } else {
        alert('No saved report found.');
      }
    } catch (e) {
      console.error("Failed to load report", e);
      alert('Failed to load report data.');
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 pb-20">
      <Header />
      
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-8">
        <div className="space-y-8">
          
          {/* Intro Text */}
          {!report && !loading && (
            <div className="text-center space-y-2 py-8">
              <h1 className="text-4xl font-bold text-slate-900 tracking-tight">
                Smart Real Estate Investment
              </h1>
              <p className="text-lg text-slate-600 max-w-2xl mx-auto">
                Make data-driven decisions in Pakistan's dynamic property market with our AI advisor.
              </p>
            </div>
          )}

          <div className="space-y-4">
            {/* Removed max-w-6xl wrapper to allow full width usage */}
            <div className="w-full">
              <AdvisorForm onSubmit={handleFormSubmit} isLoading={loading} />
            </div>
            
            {!report && !loading && (
              <div className="flex justify-center">
                <button 
                  onClick={handleLoadSaved}
                  className="flex items-center gap-2 text-sm text-slate-500 hover:text-emerald-600 transition-colors px-4 py-2 rounded-lg hover:bg-white hover:shadow-sm border border-transparent hover:border-slate-200"
                >
                  <FolderOpen size={16} />
                  Load last saved report
                </button>
              </div>
            )}
          </div>

          {error && (
            <div className="bg-rose-50 border border-rose-200 text-rose-700 p-4 rounded-xl flex items-center gap-3 animate-in fade-in max-w-6xl mx-auto">
              <AlertOctagon className="shrink-0" />
              <p>{error}</p>
            </div>
          )}

          {report && (
            <ReportView report={report} onLoadSaved={handleLoadSaved} />
          )}

          {/* Footer/Disclaimer */}
          <div className="text-center pt-12 pb-6 text-slate-400 text-xs">
            <p>
              Disclaimer: This information is generated by AI and should be used for informational purposes only. 
              Always consult with a qualified real estate professional and legal advisor before making financial decisions.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default App;
