import React from 'react';
import { 
  TrendingUp, 
  AlertTriangle, 
  CheckCircle2, 
  XCircle, 
  Info, 
  Map, 
  DollarSign,
  ShieldAlert,
  Share2,
  Save,
  FolderOpen
} from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { RealEstateReport, GrowthRatingColor } from '../types';

interface ReportViewProps {
  report: RealEstateReport;
  onLoadSaved?: () => void;
}

const formatCurrency = (val: number) => {
  if (val >= 10000000) return `${(val / 10000000).toFixed(2)} Cr`;
  if (val >= 100000) return `${(val / 100000).toFixed(2)} Lac`;
  return val.toLocaleString();
};

const CustomTooltip = ({ active, payload, label }: any) => {
  if (active && payload && payload.length) {
    return (
      <div className="bg-white p-4 border border-slate-100 rounded-xl shadow-xl shadow-slate-200/50">
        <p className="text-slate-500 font-medium text-xs uppercase tracking-wide mb-1">Year {label}</p>
        <p className="text-emerald-600 font-bold text-xl flex items-center gap-1">
           {formatCurrency(payload[0].value as number)}
        </p>
        <p className="text-xs text-slate-400 mt-1 font-medium">Estimated Value</p>
      </div>
    );
  }
  return null;
};

export const ReportView: React.FC<ReportViewProps> = ({ report, onLoadSaved }) => {
  const handleShare = async () => {
    const shareText = `🏠 PropVision AI Real Estate Report

Summary: ${report.summary}

💰 Budget Advice: ${report.adviceForBudget}

📍 Top Recommendations:
${report.bestAreas.map(area => `• ${area.name}: ${area.averagePrice} (${area.growthRating})`).join('\n')}

Generated by PropVision AI`;

    try {
      if (navigator.share) {
        await navigator.share({
          title: 'PropVision AI Report',
          text: shareText,
        });
      } else {
        await navigator.clipboard.writeText(shareText);
        alert('Report summary copied to clipboard!');
      }
    } catch (err) {
      console.error('Error sharing:', err);
    }
  };

  const handleSave = () => {
    try {
      localStorage.setItem('propVisionReport', JSON.stringify(report));
      alert('Report saved successfully!');
    } catch (e) {
      console.error('Error saving report:', e);
      alert('Failed to save report.');
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      
      {/* Summary Section */}
      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-4">
          <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2">
            <Info className="text-emerald-600" size={20} />
            Executive Summary
          </h3>
          
          <div className="flex gap-2">
            <button
              onClick={handleSave}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-slate-700 bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded-lg transition-colors active:scale-95"
              title="Save Report"
            >
              <Save size={16} className="text-emerald-600" />
              <span className="hidden sm:inline">Save</span>
            </button>
            {onLoadSaved && (
              <button
                onClick={onLoadSaved}
                className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-slate-700 bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded-lg transition-colors active:scale-95"
                title="Load Saved Report"
              >
                <FolderOpen size={16} className="text-emerald-600" />
                <span className="hidden sm:inline">Load</span>
              </button>
            )}
            <button
              onClick={handleShare}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-slate-700 bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded-lg transition-colors active:scale-95"
              title="Share Report"
            >
              <Share2 size={16} className="text-emerald-600" />
              <span className="hidden sm:inline">Share</span>
            </button>
          </div>
        </div>
        <p className="text-slate-600 leading-relaxed mb-4">{report.summary}</p>
        <div className="bg-blue-50 border border-blue-100 p-4 rounded-xl flex gap-3 items-start">
          <Info className="text-blue-600 shrink-0 mt-0.5" size={18} />
          <p className="text-sm text-blue-800">{report.adviceForBudget}</p>
        </div>
      </div>

      {/* Investment Projection Chart */}
      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
        <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2 mb-6">
          <TrendingUp className="text-emerald-600" size={20} />
          5-Year Projected Value
        </h3>
        <div className="h-[300px] w-full">
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={report.investmentPlan} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}>
              <defs>
                <linearGradient id="colorValue" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#10b981" stopOpacity={0.2}/>
                  <stop offset="95%" stopColor="#10b981" stopOpacity={0}/>
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} />
              <XAxis 
                dataKey="year" 
                stroke="#94a3b8" 
                fontSize={12} 
                tickLine={false}
                axisLine={false}
                dy={10}
              />
              <YAxis 
                stroke="#94a3b8" 
                fontSize={12}
                tickFormatter={(val) => formatCurrency(val)}
                tickLine={false}
                axisLine={false}
                dx={-10}
              />
              <Tooltip 
                content={<CustomTooltip />} 
                cursor={{ stroke: '#10b981', strokeWidth: 1, strokeDasharray: '4 4' }} 
              />
              <Area 
                type="monotone" 
                dataKey="estimatedValue" 
                stroke="#10b981" 
                strokeWidth={3}
                fillOpacity={1} 
                fill="url(#colorValue)" 
                activeDot={{ r: 6, strokeWidth: 4, stroke: '#ecfdf5', fill: '#10b981' }}
              />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Recommended Areas Grid */}
      <div>
        <h3 className="text-lg font-bold text-slate-900 flex items-center gap-2 mb-4">
          <Map className="text-emerald-600" size={20} />
          Top Recommended Areas
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {report.bestAreas.map((area, idx) => (
            <div key={idx} className="bg-white p-5 rounded-xl shadow-sm border border-slate-200 hover:shadow-md transition-shadow">
              <div className="flex justify-between items-start mb-3">
                <h4 className="font-bold text-slate-900 text-lg">{area.name}</h4>
                <span className={`px-3 py-1 rounded-full text-xs font-semibold border ${GrowthRatingColor[area.growthRating as keyof typeof GrowthRatingColor]}`}>
                  {area.growthRating} Growth
                </span>
              </div>
              <p className="text-slate-600 text-sm mb-4 line-clamp-2">{area.description}</p>
              <div className="flex items-center gap-2 text-sm font-medium text-slate-700">
                <DollarSign size={16} className="text-emerald-600" />
                Est. Price: {area.averagePrice}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Hidden Costs */}
      <div className="bg-amber-50 border border-amber-100 p-6 rounded-2xl">
        <h3 className="text-lg font-bold text-amber-900 flex items-center gap-2 mb-4">
          <AlertTriangle className="text-amber-600" size={20} />
          Hidden Costs & Taxes
        </h3>
        <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {report.hiddenCosts.map((cost, idx) => (
            <li key={idx} className="flex items-start gap-2 text-amber-800 text-sm">
              <span className="block w-1.5 h-1.5 mt-1.5 rounded-full bg-amber-500 shrink-0" />
              {cost}
            </li>
          ))}
        </ul>
      </div>

      {/* Pros & Cons */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
          <h3 className="text-lg font-bold text-emerald-900 flex items-center gap-2 mb-4">
            <CheckCircle2 className="text-emerald-600" size={20} />
            Advantages (Pros)
          </h3>
          <ul className="space-y-3">
            {report.pros.map((pro, idx) => (
              <li key={idx} className="flex items-start gap-3 text-slate-700 text-sm">
                <CheckCircle2 size={16} className="text-emerald-500 shrink-0 mt-0.5" />
                {pro}
              </li>
            ))}
          </ul>
        </div>
        
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
          <h3 className="text-lg font-bold text-rose-900 flex items-center gap-2 mb-4">
            <XCircle className="text-rose-600" size={20} />
            Risks (Cons)
          </h3>
          <ul className="space-y-3">
            {report.cons.map((con, idx) => (
              <li key={idx} className="flex items-start gap-3 text-slate-700 text-sm">
                <ShieldAlert size={16} className="text-rose-500 shrink-0 mt-0.5" />
                {con}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
};